
const list = [
    {   
        productName:'Boots',
        storeName:'KigaliStore_shoes',
        price:'$35',
        category:'ShoesForWomen',
        date:'',
        img: './project-images/boots.jpeg',
        description:'',
        status:'in stock',
    },
    {
        productName:'Boots',
        storeName:'KigaliStore_shoes',
        price:'$40',
        category:'ShoesForMen',
        date:'',
        img: './project-images/boots2.jpeg',
        description:'',
        status:'in stock',
    },
    {
        productName:'Sandals',
        storeName:'KigaliStore_shoes',
        price:'$10',
        category:'ShoesForWomen',
        date:'',
        img: './project-images/sandals.jpeg',
        description:'',
        status:'temporarily out of stock',
    },
    {
        productName:'Sandals',
        storeName:'KigaliStore_shoes',
        price:'$25',
        category:'ShoesForWomen',
        date:'',
        img: './project-images/sandals2.jpeg',
        description:'',
        status:'in stock',
    },
    {
        productName:'Jordans',
        storeName:'KigaliStore_shoes',
        price:'$35',
        category:'ShoesForMen',
        date:'',
        img: './project-images/Jordans1.jpeg',
        description:'',
        status:'in stock',
    },
    {

        productName:'Jordans',
        storeName:'KigaliStore_shoes',
        price:'$35',
        category:'ShoesForMen',
        date:'',
        img: './project-images/Jordans2.jpeg',
        description:'',
        status:'temporarily out of stock',
    },
    {
        
        productName:'Jordans',
        storeName:'KigaliStore_shoes',
        price:'$35',
        category:'ShoesForMen',
        date:'',
        img: './project-images/Jordans3.jpeg',
        description:'',
        status:'temporarily out of stock',
    },
    {
        
        productName:'Jordans',
        storeName:'KigaliStore_shoes',
        price:'$35',
        category:'ShoesForMen',
        date:'',
        img: './project-images/Jordans4.jpeg',
        description:'',
        status:'in stock',
    },
    {
        
        productName:'Jordans',
        storeName:'KigaliStore_shoes',
        price:'$35',
        category:'ShoesForMen',
        date:'',
        img: './project-images/Jordans5.jpeg',
        description:'',
        status:'in stock',
    },
    {
       
        productName:'Jordans',
        storeName:'KigaliStore_shoes',
        price:'$35',
        category:'ShoesForMen',
        date:'',
        img: './project-images/Jordans6.jpeg',
        description:'',
        status:'temporarily out of stock',
    },
    
]
export default list
